# Site
title:              Dutzu
bio:                'Dragoș DUȚU is a communication specialist interested in millennials, branding and events'
description:        "Dragoș DUȚU is a communication specialist interested in millennials, branding and events"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/dutzu-color_logo.svg'
background:         'assets/img/site-bg.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://www.dutzu.eu

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  analytics:        UA-109524666-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              dragos@dutzu.eu
twitter:            dragosdutu
#facebook:          username
#github-url:        username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           dragosdutu
#xing:              username
instagram:          dragosdutu
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#telegram:          username
keybase:            dragosdutu
#xmpp:              username@server.com
#hackernews:        username
#spotify:           username

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
