# Site
title:              "SenkOn"
bio:                "It's my little web page"
description:        "It's my little web page"
reading_time:       true
words_per_minute:   200
logo:               "assets/img/logo.png"
background:         "assets/img/placeholder-big.jpg"
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://senk0n.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
    
email:              s.shandalko@gmail.com
telegram:           senk0n
vk:                 senk0n
instagram:          senk0n
#youtube-channel:    UCxRxqC9y2R6lO3tXd8k1Izg
steam:              senk0n
#github-url:         senk0n

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
