# Site
title:              Agustín Covarrubias
bio:                'Un estudiante apasionado por la informática y la ciencia.'
description:        "Mi blog y web."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo3.png'
background:         'https://source.unsplash.com/random/1920x1080'
locale:             es_ES
url:                https://agucova.me/

# Jekyll
enforce_ssl:        agucova.me
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   agucova

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              agucova@gmail.com
twitter:            agucova
github:             agucova
stackoverflow:      4595150/forgotten-player-agucova
#linkedin:           username
#xing:              username
instagram:          agustin_covarrubias
# lastfm:             agucova
#tumblr:             username
#pinterest:         username
#foursquare:        username
#steam:              agucova
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
keybase:           agucova
#xmpp:              username@server.com
#hackernews:        username

# Gems
analytics :
  provider : google
  google :
      tracking_id : 'UA-50420608-6'
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
